CREATE DATABASE IF NOT EXISTS todo_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'todo'@'%' IDENTIFIED BY 'todo';
GRANT ALL PRIVILEGES ON todo_db.* TO 'todo'@'%';
FLUSH PRIVILEGES;
