# ============================================================================
# CRUD Operations (Create, Read, Update, Delete)
# ============================================================================
# This module handles all database operations for tasks.
# It follows the "Repository Pattern" - all database queries are centralized here.
# This makes it easy to test, modify queries, or swap databases without
# changing the API layer.
#
# The "Single Responsibility Principle" is applied - each function does ONE thing.
# ============================================================================

from sqlalchemy.orm import Session
from . import models, schemas
from typing import Optional


def create_task(db: Session, task: schemas.TaskCreate) -> models.Task:
    """Create a new task in the database.

    Takes the validated input from the client and creates a Task record.
    Returns the created task with its ID and timestamp (generated by the server).

    Args:
        db: Database session for executing queries
        task: TaskCreate schema containing title and optional description

    Returns:
        The newly created Task model object with auto-generated ID
    """
    # Create a new Task object from the provided data
    db_task = models.Task(title=task.title, description=task.description)

    # Add it to the session and commit to the database
    db.add(db_task)
    db.commit()

    # Refresh to get the auto-generated ID and timestamp from the database
    db.refresh(db_task)
    return db_task


def get_recent_tasks(db: Session, limit: int = 5) -> list[models.Task]:
    """Fetch recent incomplete tasks, ordered by creation time (newest first).

    This is typically used for the main dashboard view. We only return
    incomplete tasks and limit the results to avoid overwhelming the frontend.

    Args:
        db: Database session for executing queries
        limit: Maximum number of tasks to return (default 5)

    Returns:
        List of Task objects that are not yet completed, ordered by newest first
    """
    return (
        db.query(models.Task)
        # Filter: only get tasks that aren't completed yet
        .filter(models.Task.completed == False)
        # Sort: newest tasks first (most recent creation)
        .order_by(models.Task.created_at.desc())
        # Limit: don't return too many (API parameter)
        .limit(limit).all()
    )


def mark_task_completed(db: Session, task_id: int) -> Optional[models.Task]:
    """Mark a task as completed.

    Finds the task by ID and updates its completed status to True.
    If the task doesn't exist, returns None (caller should handle this).

    Args:
        db: Database session for executing queries
        task_id: The ID of the task to mark as done

    Returns:
        The updated Task object, or None if task was not found
    """
    # Look up the task by its ID
    task = db.query(models.Task).filter(models.Task.id == task_id).first()

    # If not found, return None (handler will return 404 error)
    if not task:
        return None

    # Update the completion status
    task.completed = True

    # Persist the change to the database
    db.commit()

    # Refresh to get any server-side updates (if any)
    db.refresh(task)
    return task
