# ============================================================================
# Data Validation Schemas (Pydantic Models)
# ============================================================================
# These schemas validate and serialize data coming in/out of the API.
# They follow the "Single Responsibility Principle" - each schema has one job:
# - TaskCreate: validates what data we need to CREATE a task
# - TaskRead: defines what data we RETURN to the client
# This separation ensures we don't accidentally expose internal fields.
# ============================================================================

from pydantic import BaseModel
from typing import Optional
from datetime import datetime


class TaskCreate(BaseModel):
    """Schema for creating a new task.

    This defines what fields a client must provide when posting a new task.
    We only accept title and optional description - the ID and timestamp
    are generated by the server.
    """

    title: str  # Task name (required)
    description: Optional[str] = None  # Additional details (optional)


class TaskRead(BaseModel):
    """Schema for returning task data to the client.

    This defines the complete task object structure that the API returns.
    We include the ID, timestamps, and all fields so the frontend has
    everything needed to display the task.
    """

    id: int  # Unique identifier for the task
    title: str  # The task name
    description: Optional[str]  # Additional details (if provided)
    completed: bool  # Whether the task is finished
    created_at: datetime  # When the task was created

    class Config:
        # orm_mode=True allows us to pass SQLAlchemy model objects directly
        # instead of dicts - Pydantic will convert them automatically
        orm_mode = True
